//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapitalEDI.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.comarch.com/", ConfigurationName="ServiceReference.EDIWebServiceSoap")]
    public interface EDIWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/Send", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapitalEDI.ServiceReference.RetRes Send(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string ControlNumber, string DocumentContent, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/Send", ReplyAction="*")]
        System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> SendAsync(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string ControlNumber, string DocumentContent, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/ListPB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapitalEDI.ServiceReference.RetRes ListPB(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/ListPB", ReplyAction="*")]
        System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ListPBAsync(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/ListPBEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapitalEDI.ServiceReference.RetRes ListPBEx(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, string OrderBy, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/ListPBEx", ReplyAction="*")]
        System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ListPBExAsync(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, string OrderBy, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/ListMB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapitalEDI.ServiceReference.RetRes ListMB(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DocumentStatus, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/ListMB", ReplyAction="*")]
        System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ListMBAsync(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DocumentStatus, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/ListMBEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapitalEDI.ServiceReference.RetRes ListMBEx(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, string DocumentStatus, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/ListMBEx", ReplyAction="*")]
        System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ListMBExAsync(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, string DocumentStatus, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/Receive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapitalEDI.ServiceReference.RetRes Receive(string Name, string Password, string PartnerIln, string DocumentType, string TrackingId, string DocumentStandard, string ChangeDocumentStatus, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/Receive", ReplyAction="*")]
        System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ReceiveAsync(string Name, string Password, string PartnerIln, string DocumentType, string TrackingId, string DocumentStandard, string ChangeDocumentStatus, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/Relationships", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapitalEDI.ServiceReference.RetRes Relationships(string Name, string Password, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/Relationships", ReplyAction="*")]
        System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> RelationshipsAsync(string Name, string Password, int Timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/ChangeDocumentStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapitalEDI.ServiceReference.RetRes ChangeDocumentStatus(string Name, string Password, string TrackingId, string Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.com/ChangeDocumentStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ChangeDocumentStatusAsync(string Name, string Password, string TrackingId, string Status);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.comarch.com/")]
    public partial class RetRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resField;
        
        private string cntField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Res {
            get {
                return this.resField;
            }
            set {
                this.resField = value;
                this.RaisePropertyChanged("Res");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Cnt {
            get {
                return this.cntField;
            }
            set {
                this.cntField = value;
                this.RaisePropertyChanged("Cnt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EDIWebServiceSoapChannel : CapitalEDI.ServiceReference.EDIWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDIWebServiceSoapClient : System.ServiceModel.ClientBase<CapitalEDI.ServiceReference.EDIWebServiceSoap>, CapitalEDI.ServiceReference.EDIWebServiceSoap {
        
        public EDIWebServiceSoapClient() {
        }
        
        public EDIWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDIWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDIWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDIWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapitalEDI.ServiceReference.RetRes Send(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string ControlNumber, string DocumentContent, int Timeout) {
            return base.Channel.Send(Name, Password, PartnerIln, DocumentType, DocumentVersion, DocumentStandard, DocumentTest, ControlNumber, DocumentContent, Timeout);
        }
        
        public System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> SendAsync(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string ControlNumber, string DocumentContent, int Timeout) {
            return base.Channel.SendAsync(Name, Password, PartnerIln, DocumentType, DocumentVersion, DocumentStandard, DocumentTest, ControlNumber, DocumentContent, Timeout);
        }
        
        public CapitalEDI.ServiceReference.RetRes ListPB(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, int Timeout) {
            return base.Channel.ListPB(Name, Password, PartnerIln, DocumentType, DocumentVersion, DocumentStandard, DocumentTest, DateFrom, DateTo, ItemFrom, ItemTo, Timeout);
        }
        
        public System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ListPBAsync(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, int Timeout) {
            return base.Channel.ListPBAsync(Name, Password, PartnerIln, DocumentType, DocumentVersion, DocumentStandard, DocumentTest, DateFrom, DateTo, ItemFrom, ItemTo, Timeout);
        }
        
        public CapitalEDI.ServiceReference.RetRes ListPBEx(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, string OrderBy, int Timeout) {
            return base.Channel.ListPBEx(Name, Password, PartnerIln, DocumentType, DocumentVersion, DocumentStandard, DocumentTest, DateFrom, DateTo, ItemFrom, ItemTo, OrderBy, Timeout);
        }
        
        public System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ListPBExAsync(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, string OrderBy, int Timeout) {
            return base.Channel.ListPBExAsync(Name, Password, PartnerIln, DocumentType, DocumentVersion, DocumentStandard, DocumentTest, DateFrom, DateTo, ItemFrom, ItemTo, OrderBy, Timeout);
        }
        
        public CapitalEDI.ServiceReference.RetRes ListMB(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DocumentStatus, int Timeout) {
            return base.Channel.ListMB(Name, Password, PartnerIln, DocumentType, DocumentVersion, DocumentStandard, DocumentTest, DocumentStatus, Timeout);
        }
        
        public System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ListMBAsync(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DocumentStatus, int Timeout) {
            return base.Channel.ListMBAsync(Name, Password, PartnerIln, DocumentType, DocumentVersion, DocumentStandard, DocumentTest, DocumentStatus, Timeout);
        }
        
        public CapitalEDI.ServiceReference.RetRes ListMBEx(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, string DocumentStatus, int Timeout) {
            return base.Channel.ListMBEx(Name, Password, PartnerIln, DocumentType, DocumentVersion, DocumentStandard, DocumentTest, DateFrom, DateTo, ItemFrom, ItemTo, DocumentStatus, Timeout);
        }
        
        public System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ListMBExAsync(string Name, string Password, string PartnerIln, string DocumentType, string DocumentVersion, string DocumentStandard, string DocumentTest, string DateFrom, string DateTo, string ItemFrom, string ItemTo, string DocumentStatus, int Timeout) {
            return base.Channel.ListMBExAsync(Name, Password, PartnerIln, DocumentType, DocumentVersion, DocumentStandard, DocumentTest, DateFrom, DateTo, ItemFrom, ItemTo, DocumentStatus, Timeout);
        }
        
        public CapitalEDI.ServiceReference.RetRes Receive(string Name, string Password, string PartnerIln, string DocumentType, string TrackingId, string DocumentStandard, string ChangeDocumentStatus, int Timeout) {
            return base.Channel.Receive(Name, Password, PartnerIln, DocumentType, TrackingId, DocumentStandard, ChangeDocumentStatus, Timeout);
        }
        
        public System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ReceiveAsync(string Name, string Password, string PartnerIln, string DocumentType, string TrackingId, string DocumentStandard, string ChangeDocumentStatus, int Timeout) {
            return base.Channel.ReceiveAsync(Name, Password, PartnerIln, DocumentType, TrackingId, DocumentStandard, ChangeDocumentStatus, Timeout);
        }
        
        public CapitalEDI.ServiceReference.RetRes Relationships(string Name, string Password, int Timeout) {
            return base.Channel.Relationships(Name, Password, Timeout);
        }
        
        public System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> RelationshipsAsync(string Name, string Password, int Timeout) {
            return base.Channel.RelationshipsAsync(Name, Password, Timeout);
        }
        
        public CapitalEDI.ServiceReference.RetRes ChangeDocumentStatus(string Name, string Password, string TrackingId, string Status) {
            return base.Channel.ChangeDocumentStatus(Name, Password, TrackingId, Status);
        }
        
        public System.Threading.Tasks.Task<CapitalEDI.ServiceReference.RetRes> ChangeDocumentStatusAsync(string Name, string Password, string TrackingId, string Status) {
            return base.Channel.ChangeDocumentStatusAsync(Name, Password, TrackingId, Status);
        }
    }
}
